version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3307:3307"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD="@Dancegym123"
      - DB_NAME=compound_lookup_db
      - PORT=3307
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "@Dancegym123"
      MYSQL_DATABASE: compound_lookup_db
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
